package com;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path="/produits") // Chemin pour correspondre aux produits
@CrossOrigin("http://localhost:8081")
public class ProduitsController {

    @Autowired // This means to get the bean called produitsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProduitsRepository produitsRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewProduit (@RequestParam String nomProduit
          ,@RequestParam Integer idFournisseur,
             @RequestParam Integer quantiteProduit) {
        Produits nouveauProduit = new Produits();
        nouveauProduit.setNomProduit(nomProduit);
        //nouveauProduit.setIdFournisseur(idFournisseur);
        nouveauProduit.setQuantiteProduit(quantiteProduit);
        produitsRepository.save(nouveauProduit);
        return "saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Produits> getAllProduits() {
        return produitsRepository.findAll();
    }
}
